[command]
default=forecast $INTERVAL $N_FORECASTS

[env]
CYLC_TASK_CYCLE_POINT=20171101T0000Z
DOMAIN=-12,48,5,61
INTERVAL=60
MAP_FILE=map.html
MAP_TEMPLATE=map-template.html
N_FORECASTS=5
RAINFALL_FILE=test-data/rainfall.csv
RESOLUTION=0.2
SPLINE_LEVEL=0
WEIGHTING=1
WIND_CYCLES=0
WIND_FILE_TEMPLATE=test-data/wind_{cycle}_{xy}.csv
