[ana:grepper.FilePattern(First Test)]
files=kgo.txt
     =results.txt
kgo_file=0
pattern='Species:\s*(\S+)'

[ana:grepper.FilePattern(Second Test)]
files=kgo.txt
     =results.txt
kgo_file=0
pattern='Class:\s*(\S+)'
