name: update tutorials

on:
  workflow_dispatch:
    inputs:
      rose_ref:
        description: The Rose branch to test against
        required: true
      fcm_ref:
        description: The FCM branch to test against
        required: false
      fcm_repo:
        description: The FCM repo to test against
        required: false
      cylc_ref:
        description: The Cylc branch to test against
        required: false
      cylc_repo:
        description: The Cylc repo to test against
        required: false
  schedule:
  - cron: '37 04 * * 1-5' # 03:37, Monday-Friday

defaults:
  run:
    shell: bash  # macos default shell is zsh

jobs:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rose_ref || github.sha }}
          path: rose

      - name: Checkout
        uses: actions/checkout@v2
        with:
          name: cylc/cylc-flow
          path: cylc

      - name: Install Rose
        run: |
          pip install cylc
          pip install rose"[all]"

      - name: Update tutorials
        run: |
          rsync -a cylc/cylc/flow/etc/tutorial/cylc-forecasting-workflow rose/metomi/rose/etc/tutorial/cylc-forecasting-suite

      - name: Test Tutorial updates
        run: |
          echo "Hello World"