name: update_tutorials

on:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '37 04 * * 1-5' # 03:37, Monday-Friday

defaults:
  run:
    shell: bash  # macos default shell is zsh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rose_ref || github.sha }}
          path: rose

      - name: Checkout
        uses: actions/checkout@v2
        with:
          name: cylc/cylc-flow
          path: cylc

      - name: Checkout
        uses: actions/checkout@v2
        with:
          name: metomi/isodatetime
          path: isodatetime

      # - name: Install repos
      #   run: |
      #     pip install isodatetime
      #     pip install cylc
      #     pip install rose

      - name: Update tutorials
        run: |
          rsync -a cylc/cylc/flow/etc/tutorial/cylc-forecasting-workflow \
            rose/metomi/rose/etc/tutorial/cylc-forecasting-suite

      - name: Test Tutorial updates
        run: |
          echo "Hello World"
