name: update_tutorials

on:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '37 04 * * 6' # 03:37, Saturday

defaults:
  run:
    shell: bash  # macos default shell is zsh

jobs:
  create-tutorials-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rose_ref || github.sha }}
          path: rose

      - name: update_tutorials
        run: |
          git clone https://github.com/cylc/cylc-flow.git
          git clone https://github.com/cylc/release-actions.git

          cp -r cylc-flow/cylc/flow/etc/tutorial/cylc-forecasting-workflow \
              cylc-forecasting-suite

          RSYNC_COMMAND=$(\
            rsync -aEim --delete cylc-forecasting-suite \
            rose/metomi/rose/etc/tutorial/\
          )

          if [ -n "${RSYNC_COMMAND}" ]; then
            echo "::set-output name=tutorials_update::True"
          else
            echo "::set-output name=tutorials_update::False"
          fi

      - name: Configure Git
        uses: cylc/release-actions/configure-git@v1

      - name: Create PR
        working-directory: rose
        if: steps.outputs.tutorials_update == 'True'
        run: |
          git checkout -b "automated-update-tutorial-workflow"

          git add .
          git commit -m "automated update of cylc tutoral suite"
          git push origin "automated-update-tutorial-workflow"
          gh pr create --title "Update Tutorial Workflow" \
            --body "This PR Pulls in changes to the tutorial workflow from cylc flow"\
            --base 2.0.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: other
        if: steps.outputs.tutorials_update == 'False'
        run: |
          echo "ran"



